name: build-protos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: install protoc
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        PB_REL="https://github.com/protocolbuffers/protobuf/releases"
        curl -LO $PB_REL/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
        sudo apt-get install unzip $unzip protoc-3.13.0-linux-x86_64.zip -d HOME/.local
        export PATH="$PATH:$HOME/.local/bin"
        protoc --version

    - name: build
      run: |
        go install github.com/golang/protobuf/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
        cd protos
        bash gen.sh
