name: build-protos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt-get install -y git
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
        sudo apt-get install unzip
        unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
        export PATH="$PATH:$HOME/.local/bin"
        protoc --version
        go install github.com/golang/protobuf/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: build proto
      run: |
        export PATH="$PATH:$HOME/.local/bin"
        protoc --version
        cd protos
        bash gen.sh
        ls -al

    - name: add ssh
      run: |

    - name: upload proto
      run: |
        cd protos
        git init
        git config --local user.name "duc"
        git config --local user.email "1025434218@qq.com"
        git add .
        git commit -m "commit protos"
        git remote add origin https://github.com/DuC-cnZj/order_protos.git
        git remote set-url --push origin https://DuC-cnZj:${{ secrets.TOKEN }}@github.com/DuC-cnZj/order_protos.git
        git push -u origin master
